// Typed access to the CARTO-computed impact figures.
//
// Source of truth: src/content/impact/*.json, generated by the CARTO analysis
// (scripts/impact-analysis.sql -> scripts/build-impact-data.mjs). Re-run that
// pipeline when the facility set changes; do not hand-edit the JSON.
//
// All figures derive from public-domain inputs (USGS water-service areas + US
// Census county boundaries), so they are safe to cite next to legal content.

import statewideData from "@/content/impact/statewide.json";
import byCountyData from "@/content/impact/by-county.json";
import byFacilityData from "@/content/impact/by-facility.json";

export interface StatewideImpact {
  totalDataCenters: number;
  inWaterDistrict: number;
  notInWaterDistrict: number;
  distinctAffectedDistricts: number;
  populationServedByAffectedDistricts: number;
  countiesWithDataCenters: number;
  generatedAt: string;
  source: string;
}

export interface CountyImpact {
  county: string;
  totalDataCenters: number;
  operating: number;
  underConstruction: number;
  proposed: number;
  permitted: number;
  inWaterDistrict: number;
  affectedDistricts: number;
  populationInAffectedDistricts: number;
}

export interface FacilityImpact {
  slug: string;
  name: string;
  operator: string;
  city: string | null;
  county: string;
  status: string;
  inWaterDistrict: boolean;
  waterDistrictName: string | null;
  waterDistrictPopulationServed: number | null;
}

export const statewideImpact = statewideData as unknown as StatewideImpact;

const counties = (
  byCountyData as unknown as { counties: Record<string, CountyImpact> }
).counties;
const facilities = (
  byFacilityData as unknown as { facilities: Record<string, FacilityImpact> }
).facilities;

/** Impact figures for one county. Accepts "Bell County" or "Bell". */
export function getCountyImpact(name: string): CountyImpact | undefined {
  if (!name) return undefined;
  if (counties[name]) return counties[name];
  // tolerate bare county names ("Bell" -> "Bell County")
  const withSuffix = `${name} County`;
  if (counties[withSuffix]) return counties[withSuffix];
  const lower = name.toLowerCase();
  return Object.values(counties).find(
    (c) => c.county.toLowerCase() === lower || c.county.toLowerCase() === `${lower} county`,
  );
}

/** Impact figures for one facility, by its content slug. */
export function getFacilityImpact(slug: string): FacilityImpact | undefined {
  return slug ? facilities[slug] : undefined;
}

export function allCountyImpacts(): CountyImpact[] {
  return Object.values(counties);
}

/** "5,254,616" -> "5.25M"; smaller numbers shown with thousands separators. */
export function formatPeople(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 10_000) return `${(n / 1_000).toFixed(0)}K`;
  return n.toLocaleString("en-US");
}
